In [1]:
import numpy as np

In [2]:
arr = np.array([23,45,88,53,67,89,12,56])

In [3]:
arr.shape

(8,)

In [6]:
arr[2]

88

In [7]:
arr[5]

89

In [8]:
arr[2:6]

array([88, 53, 67, 89])

In [9]:
arr[5:]

array([89, 12, 56])

In [10]:
arr

array([23, 45, 88, 53, 67, 89, 12, 56])

In [11]:
arr[:4]

array([23, 45, 88, 53])

In [12]:
np.random.randint(1,100,25)

array([ 3, 19, 78, 27, 28, 68, 50, 51, 35, 45,  3, 74, 99,  7, 80, 79, 25,
       26, 70, 89, 32, 18, 46, 84,  7])

In [13]:
arr2 = np.random.randint(1,100,25)

In [14]:
arr2

array([96, 10, 75, 81, 15, 78,  5, 17, 27, 81,  3, 99, 87, 96, 93, 99, 94,
       44,  4, 65,  8, 70, 44, 91, 50])

In [15]:
arr2.shape

(25,)

In [16]:
arr3 = arr2.reshape(5,5)

In [17]:
arr3

array([[96, 10, 75, 81, 15],
       [78,  5, 17, 27, 81],
       [ 3, 99, 87, 96, 93],
       [99, 94, 44,  4, 65],
       [ 8, 70, 44, 91, 50]])

In [18]:
arr3.shape

(5, 5)

In [19]:
arr3[1:3,2:]

array([[17, 27, 81],
       [87, 96, 93]])

In [20]:
arr3[2:4,1:3]

array([[99, 87],
       [94, 44]])

In [21]:
arr3[:,0]

array([96, 78,  3, 99,  8])

In [22]:
arr3

array([[96, 10, 75, 81, 15],
       [78,  5, 17, 27, 81],
       [ 3, 99, 87, 96, 93],
       [99, 94, 44,  4, 65],
       [ 8, 70, 44, 91, 50]])

In [23]:
arr3[:,[0]]

array([[96],
       [78],
       [ 3],
       [99],
       [ 8]])

In [24]:
arr3[:,[0]].shape

(5, 1)

In [25]:
arr3

array([[96, 10, 75, 81, 15],
       [78,  5, 17, 27, 81],
       [ 3, 99, 87, 96, 93],
       [99, 94, 44,  4, 65],
       [ 8, 70, 44, 91, 50]])

In [26]:
arr3[:,[1,2]]

array([[10, 75],
       [ 5, 17],
       [99, 87],
       [94, 44],
       [70, 44]])

In [27]:
arr3[:,1:3]

array([[10, 75],
       [ 5, 17],
       [99, 87],
       [94, 44],
       [70, 44]])

In [28]:
arr3

array([[96, 10, 75, 81, 15],
       [78,  5, 17, 27, 81],
       [ 3, 99, 87, 96, 93],
       [99, 94, 44,  4, 65],
       [ 8, 70, 44, 91, 50]])

In [29]:
arr3[2]

array([ 3, 99, 87, 96, 93])

In [30]:
arr4 = np.array([1,2,3,4,4,5,3,3])

In [31]:
arr4

array([1, 2, 3, 4, 4, 5, 3, 3])

In [32]:
arr4.shape

(8,)

In [33]:
np.mean(arr4)

3.125

In [34]:
np.var(arr4)

1.359375

In [35]:
np.std(arr4)

1.165922381636102

In [36]:
np.sin(arr4)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.7568025 ,
       -0.95892427,  0.14112001,  0.14112001])

In [37]:
np.cos(arr4)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362, -0.65364362,
        0.28366219, -0.9899925 , -0.9899925 ])

In [38]:
np.log(arr4)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.38629436,
       1.60943791, 1.09861229, 1.09861229])

In [39]:
np.exp(arr4)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
        54.59815003, 148.4131591 ,  20.08553692,  20.08553692])

In [40]:
# Pandas

In [47]:
my_list = [23,366,42]

In [48]:
label = ['a','b','c']

In [49]:
d = {'x':234,'y':56,'z':567}

In [50]:
d

{'x': 234, 'y': 56, 'z': 567}

In [51]:
arr1 = np.array([255,67,890])

In [54]:
import pandas as pd

NameError: name 'ser1' is not defined